name: Publish to Test.Pypi

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-uv

      - name: Build
        run: uv build

      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel & source distribution)
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          uv run --isolated --no-project --with dist/fpdf2_textindex-${VERSION}-py3-none-any.whl test/smoke_test.py
          uv run --isolated --no-project --with dist/fpdf2_textindex-${VERSION}.tar.gz test/smoke_test.py

      - name: Check existing versions
        run: |
          echo Versions already released on TestPypi: $(curl -Ls 'https://test.pypi.org/pypi/fpdf2_textindex/json' | jq -r '.releases|keys[]')
          VERSION=$(uv run python -c "import importlib.metadata; print(importlib.metadata.version('fpdf2_textindex'))")
          echo Current code version: $VERSION
          # Checking if current code version has already been released:
          if ! curl -Ls "https://test.pypi.org/pypi/fpdf2_textindex/json" \
            | jq -r '.releases|keys[]' \
            | grep "^$VERSION$"; then
            echo "publish=yes" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish
        if: steps.build.outputs.publish == 'yes'
        run: uv publish --index testpypi
